# Generated by Django 4.1.13 on 2024-06-12 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fisioterapeutas',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Motivos',
            fields=[
                ('motivoID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('movimientoID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=255)),
                ('nombre2', models.CharField(blank=True, max_length=255)),
                ('apellido1', models.CharField(max_length=255)),
                ('apellido2', models.CharField(blank=True, max_length=255)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rehabilitaciones',
            fields=[
                ('rehabilitacionID', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField(null=True)),
                ('fechaFin', models.DateField(null=True)),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapias.fisioterapeutas')),
                ('motivoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapias.motivos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapias.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='Terapias',
            fields=[
                ('terapiaID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('rehabilitacionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapias.rehabilitaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('sesionID', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
                ('porcentaje', models.FloatField(null=True)),
                ('repeticiones', models.CharField(max_length=255)),
                ('movimientoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapias.movimientos')),
                ('terapiaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapias.terapias')),
            ],
        ),
    ]
