# Generated by Django 4.1.13 on 2024-06-21 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terapias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leapMotion',
            fields=[
                ('registroID', models.AutoField(primary_key=True, serialize=False)),
                ('repeticion', models.IntegerField()),
                ('resultado', models.IntegerField()),
                ('arrayDatos', models.JSONField()),
                ('sesionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapias.sesiones')),
            ],
        ),
    ]
