# Generated by Django 5.0.6 on 2024-05-30 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='contrasena',
        ),
    ]
