# Generated by Django 4.1.13 on 2024-06-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leapmotion',
            name='arrayDatos',
        ),
    ]
