# Generated by Django 5.0.4 on 2024-05-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapias', '0002_remove_pacientes_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisioterapeutas',
            name='email',
            field=models.CharField(default='example@example.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
